blank_issues_enabled: false
contact_links:
  - name: Feature Request / Contribution Inquiry
    url: https://github.com/turkovich/microprism-glass/blob/main/.github/PULL_REQUEST_TEMPLATE.md
    about: Please read our contribution policy before opening issues. We generally do not accept feature PRs.